VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Parts"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public aplisns As New Collection

Public cagePart As String
Public cage As String
Public part As String
Public count As Integer
Public descrip  As String
Public nsn As String
